spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:postgresql://localhost:5432/e_commerce
    username: postgres
    password: 2334
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
